// Code generated by "stringer -type=Interpolation -trimprefix Interpolation"; DO NOT EDIT.

package ippresize

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterpolationNearestNeighbour-1]
	_ = x[InterpolationLinear-2]
	_ = x[InterpolationCubic-3]
	_ = x[InterpolationLanczos-4]
	_ = x[InterpolationSuper-5]
	_ = x[InterpolationAntialiasingLinear-6]
	_ = x[InterpolationAntialiasingCubic-7]
	_ = x[InterpolationAntialiasingLanczos-8]
}

const _Interpolation_name = "NearestNeighbourLinearCubicLanczosSuperAntialiasingLinearAntialiasingCubicAntialiasingLanczos"

var _Interpolation_index = [...]uint8{0, 16, 22, 27, 34, 39, 57, 74, 93}

func (i Interpolation) String() string {
	i -= 1
	if i >= Interpolation(len(_Interpolation_index)-1) {
		return "Interpolation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Interpolation_name[_Interpolation_index[i]:_Interpolation_index[i+1]]
}
