// Code generated by "stringer -type=IppStatus"; DO NOT EDIT.

package ippresize

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IppStsSizeErr - -6]
}

const _IppStatus_name = "IppStsSizeErr"

var _IppStatus_index = [...]uint8{0, 13}

func (i IppStatus) String() string {
	i -= -6
	if i < 0 || i >= IppStatus(len(_IppStatus_index)-1) {
		return "IppStatus(" + strconv.FormatInt(int64(i+-6), 10) + ")"
	}
	return _IppStatus_name[_IppStatus_index[i]:_IppStatus_index[i+1]]
}
